<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\IdPrefixSetting;

class IdPrefixSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $prefixSettings = [
            [
                'entity_type' => 'patient',
                'company_prefix' => 'HWC',
                'module_prefix' => 'PAT',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Patient ID pattern: HWC/PAT/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'appointment',
                'company_prefix' => 'HWC',
                'module_prefix' => 'APT',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Appointment ID pattern: HWC/APT/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'consultation',
                'company_prefix' => 'HWC',
                'module_prefix' => 'CON',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Consultation ID pattern: HWC/CON/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'lab_test',
                'company_prefix' => 'HWC',
                'module_prefix' => 'LAB',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Lab Test ID pattern: HWC/LAB/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'lab_result',
                'company_prefix' => 'HWC',
                'module_prefix' => 'RES',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Lab Result ID pattern: HWC/RES/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'invoice',
                'company_prefix' => 'HWC',
                'module_prefix' => 'INV',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Invoice ID pattern: HWC/INV/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'payment',
                'company_prefix' => 'HWC',
                'module_prefix' => 'PAY',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Payment ID pattern: HWC/PAY/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'prescription',
                'company_prefix' => 'HWC',
                'module_prefix' => 'RX',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Prescription ID pattern: HWC/RX/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'scan',
                'company_prefix' => 'HWC',
                'module_prefix' => 'SCN',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Scan ID pattern: HWC/SCN/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'store_order',
                'company_prefix' => 'HWC',
                'module_prefix' => 'ORD',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Store Order ID pattern: HWC/ORD/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'drug',
                'company_prefix' => 'HWC',
                'module_prefix' => 'DRG',
                'pattern' => '{company_prefix}/{module_prefix}/{sequence}',
                'sequence_length' => 6,
                'current_sequence' => 0,
                'include_year' => false,
                'include_month' => false,
                'include_day' => false,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Drug ID pattern: HWC/DRG/000001'
            ],
            [
                'entity_type' => 'ward',
                'company_prefix' => 'HWC',
                'module_prefix' => 'WRD',
                'pattern' => '{company_prefix}/{module_prefix}/{sequence}',
                'sequence_length' => 3,
                'current_sequence' => 0,
                'include_year' => false,
                'include_month' => false,
                'include_day' => false,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Ward ID pattern: HWC/WRD/001'
            ],
            [
                'entity_type' => 'bed',
                'company_prefix' => 'HWC',
                'module_prefix' => 'BED',
                'pattern' => '{company_prefix}/{module_prefix}/{sequence}',
                'sequence_length' => 4,
                'current_sequence' => 0,
                'include_year' => false,
                'include_month' => false,
                'include_day' => false,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Bed ID pattern: HWC/BED/0001'
            ],
            [
                'entity_type' => 'branch',
                'company_prefix' => 'HWC',
                'module_prefix' => 'BRN',
                'pattern' => '{company_prefix}/{module_prefix}/{sequence}',
                'sequence_length' => 3,
                'current_sequence' => 0,
                'include_year' => false,
                'include_month' => false,
                'include_day' => false,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Branch ID pattern: HWC/BRN/001'
            ],
            [
                'entity_type' => 'staff',
                'company_prefix' => 'HWC',
                'module_prefix' => 'STF',
                'pattern' => '{company_prefix}/{module_prefix}/{sequence}',
                'sequence_length' => 4,
                'current_sequence' => 0,
                'include_year' => false,
                'include_month' => false,
                'include_day' => false,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Staff ID pattern: HWC/STF/0001'
            ],
            [
                'entity_type' => 'doctor',
                'company_prefix' => 'HWC',
                'module_prefix' => 'DOC',
                'pattern' => '{company_prefix}/{module_prefix}/{sequence}',
                'sequence_length' => 4,
                'current_sequence' => 0,
                'include_year' => false,
                'include_month' => false,
                'include_day' => false,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Doctor ID pattern: HWC/DOC/0001'
            ],
            [
                'entity_type' => 'expense',
                'company_prefix' => 'HWC',
                'module_prefix' => 'EXP',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Expense ID pattern: HWC/EXP/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'revenue',
                'company_prefix' => 'HWC',
                'module_prefix' => 'REV',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Revenue transaction ID pattern: HWC/REV/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'complaint',
                'company_prefix' => 'HWC',
                'module_prefix' => 'CMP',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Complaint ID pattern: HWC/CMP/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'queue',
                'company_prefix' => 'HWC',
                'module_prefix' => 'QUE',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Queue ID pattern: HWC/QUE/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'delivery',
                'company_prefix' => 'HWC',
                'module_prefix' => 'DEL',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Delivery ID pattern: HWC/DEL/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'drug_order',
                'company_prefix' => 'HWC',
                'module_prefix' => 'DRO',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Drug Order ID pattern: HWC/DRO/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'order_item',
                'company_prefix' => 'HWC',
                'module_prefix' => 'OIT',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Order Item ID pattern: HWC/OIT/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'staff_profile',
                'company_prefix' => 'HWC',
                'module_prefix' => 'STP',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Staff Profile ID pattern: HWC/STP/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'supplier',
                'company_prefix' => 'HWC',
                'module_prefix' => 'SUP',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Supplier ID pattern: HWC/SUP/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'diagnosis',
                'company_prefix' => 'HWC',
                'module_prefix' => 'DIA',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Diagnosis ID pattern: HWC/DIA/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'vital',
                'company_prefix' => 'HWC',
                'module_prefix' => 'VIT',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Vital ID pattern: HWC/VIT/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'note',
                'company_prefix' => 'HWC',
                'module_prefix' => 'NOT',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Note ID pattern: HWC/NOT/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'follow_up',
                'company_prefix' => 'HWC',
                'module_prefix' => 'FLU',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Follow Up ID pattern: HWC/FLU/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'referral',
                'company_prefix' => 'HWC',
                'module_prefix' => 'REF',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Referral ID pattern: HWC/REF/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'pharmacy_purchase_order',
                'company_prefix' => 'HWC',
                'module_prefix' => 'PPO',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Pharmacy Purchase Order: HWC/PPO/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'lab_purchase_order',
                'company_prefix' => 'HWC',
                'module_prefix' => 'LPO',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Lab Purchase Order: HWC/LPO/YYYYMMDD/00001'
            ],
            [
                'entity_type' => 'radiology_purchase_order',
                'company_prefix' => 'HWC',
                'module_prefix' => 'RPO',
                'pattern' => '{company_prefix}/{module_prefix}/{year}{month}{day}/{sequence}',
                'sequence_length' => 5,
                'current_sequence' => 0,
                'include_year' => true,
                'include_month' => true,
                'include_day' => true,
                'separator' => '/',
                'is_locked' => false,
                'is_active' => true,
                'description' => 'Radiology Purchase Order: HWC/RPO/YYYYMMDD/00001'
            ],
        ];

        foreach ($prefixSettings as $setting) {
            $entityType = $setting['entity_type'];
            $initialSequence = $setting['current_sequence'] ?? 0;
            unset($setting['entity_type'], $setting['current_sequence']);

            $model = IdPrefixSetting::firstOrNew(['entity_type' => $entityType]);
            $model->fill($setting);
            if (!$model->exists) {
                $model->current_sequence = $initialSequence;
            }
            $model->save();
        }
    }
}